name: github_graphql_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  # for ease of use of Navigator 2.0
  go_router: ^17.0.1
  # for state management
  bloc: ^9.2.0
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  # for encrypted storage
  flutter_secure_storage: ^10.0.0
  # for rendering svgs
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  graphql_flutter: ^5.1.2
  http: ^1.2.2
  # for using oauth services
  json_annotation: ^4.9.0
  oauth2: ^2.0.0
  # open webview inside app
  path_provider: ^2.0.11
  webview_flutter: ^4.9.0
  flutter_markdown: ^0.7.4+3
  url_launcher: ^6.3.1
  web: ^1.1.1
  js: ^0.7.2

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^2.5.7
  json_serializable: ^6.3.1
  test: ^1.25.15

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svgs/
